version: '2'

services:
  ci-restore:
    build:
      context: .
      dockerfile: Dockerfile.ci.restore
    image: mls-ls/restored
  ci-build:
    depends_on:
      - ci-restore
    build:
      context: .
      dockerfile: Dockerfile.ci.build
    image: mls-ls/built
  ci-publish-mls.agent:
    depends_on:
      - ci-build
    image: mls-ls/built
    volumes:
      - ./MLS.Agent/obj/Docker:/app/MLS.Agent/obj/Docker
    command: dotnet publish ./MLS-LS.sln -c Release -o ./obj/Docker/publish
  ci-test-mls.agent:
    depends_on:
      - ci-build
    image: mls-ls/built
    volumes:
      - ./MLS.Agent.Tests/TestResults:/app/MLS.Agent.Tests/TestResults
    command: dotnet test /app/MLS.Agent.Tests/MLS.Agent.Tests.csproj --logger trx 
  ci-test-languageserver:
    depends_on:
      - ci-build
    image: mls-ls/built
    volumes:
      - ./LanguageServer.Tests/TestResults:/app/LanguageServer.Tests/TestResults
    command: dotnet test /app/LanguageServer.Tests/LanguageServer.Tests.csproj --logger trx 